/*
 *    Copyright 2026 Adrian Paskert
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

#[cfg(any(target_arch="x86_64", target_arch="x86"))]
mod x86;
#[cfg(any(target_os="linux", target_os="macos", target_os="freebsd", target_os="openbsd"))]
mod unix;
mod signal_stack;
mod cfi;

use std::cell::{LazyCell, RefCell};
use std::hash::DefaultHasher;
use std::ops::Index;
use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::Mutex;
use log::error;
use edlc_core::prelude::{AmorphusDataCopy, HirPhase, MirPhase, TypeArgument, TypeArguments};
use edlc_core::prelude::mir_backend::Backend;
use edlc_core::prelude::mir_funcs::MirFuncRegistry;
use edlc_core::prelude::mir_type::MirTypeId;
#[cfg(any(target_os="linux", target_os="macos", target_os="freebsd", target_os="openbsd"))]
pub use unix::TrapHandler;
use crate::compiler::{UnwindInfo, JIT};

#[derive(Default, Clone, Copy, Debug)]
pub struct BacktraceEntry {
    /// Code offset of the panic (from the base addr).
    loc: usize,
    /// Function pointer in which the location lives.
    /// This is guaranteed to always be a function generated by the JIT.
    func: usize,
}

pub struct Backtrace {
    trace: Box<[BacktraceEntry]>,
    len: usize,
}


const BACKTRACE_SIZE_MAX: usize = 32;

impl Backtrace {
    fn new() -> Self {
        let trace = vec![const { BacktraceEntry {
            loc: 0,
            func: 0,
        } }; BACKTRACE_SIZE_MAX];
        Backtrace {
            trace: trace.into_boxed_slice(),
            len: 0,
        }
    }

    fn push(&mut self, entry: BacktraceEntry) {
        if self.len >= BACKTRACE_SIZE_MAX {
            return;
        }
        self.trace[self.len] = entry;
        self.len += 1;
    }

    fn slice(&self) -> &[BacktraceEntry] {
        &self.trace[..self.len]
    }

    fn clear(&mut self) {
        self.len = 0;
    }

    fn len(&self) -> usize {
        self.len
    }

    fn is_empty(&self) -> bool {
        self.len == 0
    }

    fn print<B: Backend>(
        &self,
        phase: &HirPhase,
        funcs: &MirFuncRegistry<B>,
        debug_frames: &UnwindInfo,
    ) {
        for trace in self.slice() {
            if let Some(id) = debug_frames.find_id(&trace.func) {
                let edl_func = funcs.get_edl_id(id)
                    .expect("failed to get EDL function id from MIR function id");
                let sig = phase.types.get_fn_signature(edl_func)
                    .expect("failed to get function signature");

                if let Some((pos, src)) = funcs.get_source_information(id) {
                    error!("    {} at {}", TypeArguments::<'_, DefaultHasher>::new(&[
                        TypeArgument::new_edl(sig)
                    ]).printable(&phase.types, &phase.vars), src.format_pos(pos));
                } else {
                    error!("    {}", TypeArguments::<'_, DefaultHasher>::new(&[
                        TypeArgument::new_edl(sig),
                    ]).printable(&phase.types, &phase.vars));
                }
                error!("        at offset {:p}", trace.loc as *const ());
            } else {
                error!("    <unknown> {:p}", trace.func as *const ());
                error!("        at offset {:p}", trace.loc as *const ());
            }
        }
    }
}

impl Index<usize> for Backtrace {
    type Output = BacktraceEntry;

    fn index(&self, index: usize) -> &Self::Output {
        self.trace.get(index).unwrap()
    }
}

struct PanicPayload {
    backtrace: Backtrace,
    reached_host: bool,
}

impl PanicPayload {
    fn clear(&mut self) {
        self.backtrace.clear();
        self.reached_host = false;
    }
}

/// Encodes information about a panic.
pub struct PanicData {
    panic: AtomicBool,
    payload: Mutex<PanicPayload>,
}

thread_local! {
    static PANIC: LazyCell<PanicData> = LazyCell::new(PanicData::new);
}

impl PanicData {
    fn new() -> PanicData {
        PanicData {
            panic: AtomicBool::new(false),
            payload: Mutex::new(PanicPayload {
                backtrace: Backtrace::new(),
                reached_host: false,
            }),
        }
    }

    /// Sets the panic data.
    /// If this function is called, the host's safety features will assume that the JIT code paniced
    /// and the stack was unrolled into this collection of panic data.
    fn set<R, F: FnOnce(&mut PanicPayload) -> R>(with: F, default: R) -> R {
        PANIC.with(|panic| {
            panic.panic.store(true, Ordering::Relaxed);
            if let Ok(mut backtrace) = panic.payload.lock() {
                backtrace.clear();
                with(&mut backtrace)
            } else {
                default
            }
        })
    }

    /// Fetches the local panic handling data from thread local storage.
    /// If there was no panic since the last time this function was called, it will return `None`.
    pub fn fetch<Runtime: 'static>(jit: &JIT<Runtime>, hir_phase: &HirPhase) -> Result<(), PanicError> {
        PANIC.with(|panic| if panic
            .panic
            .fetch_and(false, Ordering::Relaxed) {

            let payload = panic.payload.lock().unwrap();
            error!("encountered panic while executing JIT code in thread: {}",
                std::thread::current().name().unwrap_or("unknown"));
            error!("stack trace:");
            payload.backtrace.print(hir_phase, &*jit.func_reg.borrow(), &jit.unwind_info);
            error!("end of stack trace.");
            if payload.reached_host {
                error!("host function reached – attempting to recover through graceful panic protocol");
            } else {
                error!("host function was not reached during unwinding – graceful panic not possible");
                panic!("unrecoverable panic during JIT code execution");
            }

            let msg = PanicMessage::take().map(|msg| msg.data);
            Err(PanicError {
                msg,
                graceful: payload.reached_host,
                panic_type: PanicType::Explicit,
            })
        } else {
            Ok(())
        })
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum PanicType {
    DivideByZero,
    ArrayIndexOutOfBounds,
    SliceIndexOutOfBounds,
    ArrayRangeOutOfBounds,
    SliceRangeOutOfBounds,
    Assertion,
    Explicit,
    Segfault,
}

#[derive(Debug)]
pub struct PanicError {
    pub msg: Option<String>,
    pub graceful: bool,
    pub panic_type: PanicType,
}

/// User-defined panic message, that can be passed to a manual call to core::panic.
pub struct PanicMessage {
    pub data: String,
}

thread_local! {
    static PANIC_MSG: RefCell<Option<PanicMessage>> = const { RefCell::new(None) };
}

impl PanicMessage {
    pub fn set(msg: PanicMessage) {
        PANIC_MSG.set(Some(msg));
    }

    fn take() -> Option<PanicMessage> {
        PANIC_MSG.take()
    }
}
