/*
 * EDLc, a compiler for the EDL programming language.
 * Copyright (C) 2026  Adrian Paskert
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
//! MCP server implementation for EDL documentation.
//!
//! Exposes five tools over the Model Context Protocol, over stdio (the default local transport,
//! [`serve_stdio`]) or Streamable HTTP on a TCP socket (the spec's network transport,
//! [`serve_http`], endpoint `/mcp`):
//!
//! - `search_docs(query, limit?, kind?, details?)` — full-text search across item names,
//!   modules, signatures, and doc text.
//! - `get_doc(name, details?)` — fetch a single documentation item by its (qualified) name.
//! - `list_modules(details?)` — list all modules in the database.
//! - `get_module(name, details?)` — list all items belonging to a module.
//! - `list_items(kind?, details?)` — list all items in the database, including crate-root items.
//!
//! ## What is MCP?
//!
//! The [Model Context Protocol](https://modelcontextprotocol.io/) is a standard protocol for
//! exposing tools, resources, and prompts to AI assistants. An MCP client (e.g. Claude Desktop,
//! Cursor, or any MCP-compatible LLM) launches this server as a child process and communicates
//! over stdin/stdout using JSON-RPC. The client can then call the tools listed above to search
//! and retrieve EDL documentation on behalf of the user.

use rmcp::{
    handler::server::{router::tool::ToolRouter, wrapper::Parameters},
    model::{ServerCapabilities, ServerInfo},
    transport::streamable_http_server::{
        session::local::LocalSessionManager, StreamableHttpServerConfig, StreamableHttpService,
    },
    schemars, tool, tool_handler, tool_router, ServerHandler, ServiceExt,
};
use serde::{Deserialize, Serialize};
use std::sync::{Arc, Mutex};

use edlc_doc_db::{DocDb, DocRow};

/// The MCP server. Holds a shared read-only handle to the documentation database and a
/// tool router generated by the `#[tool_router]` macro.
///
/// `DocDb` contains a `rusqlite::Connection` which is `Send` but not `Sync`. We wrap it in
/// `std::sync::Mutex` to satisfy the `ServerHandler: Sync` bound. The lock is never held across
/// an `.await` point — all DB work goes through `tokio::task::spawn_blocking`.
pub struct DocMcpServer {
    db: Arc<Mutex<DocDb>>,
    /// Generated by `#[tool_router]` — stores tool metadata for dispatch.
    tool_router: ToolRouter<Self>,
}

impl DocMcpServer {
    /// Creates a new MCP server backed by the given database.
    pub fn new(db: DocDb) -> Self {
        Self::from_handle(Arc::new(Mutex::new(db)))
    }

    /// Creates an MCP server sharing an existing database handle. The Streamable HTTP transport
    /// constructs one handler per client session, so all sessions share one `DocDb` connection.
    pub fn from_handle(db: Arc<Mutex<DocDb>>) -> Self {
        DocMcpServer {
            db,
            tool_router: Self::tool_router(),
        }
    }
}

// --- Tool parameter structs ---

#[derive(Debug, Deserialize, schemars::JsonSchema)]
struct SearchDocsParams {
    /// The search query. Each whitespace-separated token must match a token prefix in an item
    /// name, module path, signature, or doc text (implicit AND), using SQLite FTS5 full-text
    /// search — e.g. `add ov` matches `add_overflow`.
    query: String,
    /// Maximum number of results to return. Defaults to 20.
    #[serde(default = "default_search_limit")]
    limit: usize,
    /// Optional kind filter: one of `fn`, `let`, `const`, `type`, `module`.
    #[serde(default)]
    kind: Option<String>,
    /// When true, include the full structured `blob` of each item in the results. Defaults to
    /// false — the `signature` and `doc_text` fields usually suffice for writing code.
    #[serde(default)]
    details: bool,
}

fn default_search_limit() -> usize {
    20
}

#[derive(Debug, Deserialize, schemars::JsonSchema)]
struct GetDocParams {
    /// The name of the item to fetch. Prefer a qualified name (e.g. "example::add"); a simple
    /// name (e.g. "add") is ambiguous when several items share it, in which case the response
    /// lists the candidate qualified names to retry with.
    name: String,
    /// When true, include the full structured `blob` of the item. Defaults to false.
    #[serde(default)]
    details: bool,
}

#[derive(Debug, Deserialize, schemars::JsonSchema)]
struct GetModuleParams {
    /// The name of the module whose items should be listed.
    name: String,
    /// When true, include the full structured `blob` of each item. Defaults to false.
    #[serde(default)]
    details: bool,
}

#[derive(Debug, Deserialize, schemars::JsonSchema)]
struct ListModulesParams {
    /// When true, include the full structured `blob` of each module. Defaults to false.
    #[serde(default)]
    details: bool,
}

#[derive(Debug, Deserialize, schemars::JsonSchema)]
struct ListItemsParams {
    /// Optional kind filter: one of `fn`, `let`, `const`, `type`, `module`.
    #[serde(default)]
    kind: Option<String>,
    /// When true, include the full structured `blob` of each item. Defaults to false.
    #[serde(default)]
    details: bool,
}

// --- Result type ---

#[derive(Debug, Serialize)]
struct DocSummary {
    id: i64,
    kind: String,
    name: String,
    qual_name: String,
    module: Option<String>,
    signature: String,
    doc_text: String,
    /// The full serde-JSON of the original `Item`, containing all structured fields including
    /// `async_return`, `modifiers`, params, etc. Only present when the tool is called with
    /// `details: true`.
    #[serde(skip_serializing_if = "Option::is_none")]
    blob: Option<String>,
}

/// Converts a database row into a summary, including the `blob` only when `details` is set.
fn row_to_summary(row: DocRow, details: bool) -> DocSummary {
    DocSummary {
        id: row.id,
        kind: row.kind.as_str().to_string(),
        name: row.name,
        qual_name: row.qual_name,
        module: row.module,
        signature: row.signature,
        doc_text: row.doc_text,
        blob: details.then(|| row.blob),
    }
}

/// Validates a user-supplied kind filter string.
fn parse_kind(kind: &str) -> Result<edlc_doc_db::Kind, String> {
    edlc_doc_db::Kind::parse(kind).ok_or_else(|| {
        format!("unknown kind '{kind}' (expected one of: fn, let, const, type, module)")
    })
}

fn error_json(msg: &str) -> String {
    serde_json::to_string_pretty(&serde_json::json!({ "error": msg })).unwrap()
}

// --- Tools ---

#[tool_router]
impl DocMcpServer {
    /// Search EDL documentation by full-text query.
    #[tool(
        description = "Search EDL documentation items by full-text query (prefix matching: each token must match a token prefix; 'add ov' matches 'add_overflow'). Use this to discover APIs. Returns up to `limit` best matches (default 20) with their signatures and doc text, names ranked highest. Optionally filter by `kind` (fn, let, const, type, module). Pass `details: true` to also get each item's full structured blob."
    )]
    async fn search_docs(
        &self,
        Parameters(SearchDocsParams {
            query,
            limit,
            kind,
            details,
        }): Parameters<SearchDocsParams>,
    ) -> String {
        let kind = match kind.as_deref().map(parse_kind).transpose() {
            Ok(k) => k,
            Err(e) => return error_json(&e),
        };
        let db = self.db.clone();
        let result = tokio::task::spawn_blocking(move || {
            let guard = db.lock().map_err(|e| e.to_string())?;
            guard.search(&query, limit, kind).map_err(|e| e.to_string())
        })
        .await;

        match result {
            Ok(Ok(rows)) => {
                let summaries: Vec<DocSummary> = rows
                    .into_iter()
                    .map(|row| row_to_summary(row, details))
                    .collect();
                serde_json::to_string_pretty(&summaries)
                    .unwrap_or_else(|e| error_json(&e.to_string()))
            }
            Ok(Err(e)) => error_json(&e),
            Err(e) => error_json(&e.to_string()),
        }
    }

    /// Get a single documentation item by name.
    #[tool(
        description = "Fetch a single EDL documentation item by name. Prefer a qualified name (e.g. 'example::add'): if a simple name matches several items (overloads), the response is an error listing the candidate qualified names — retry with one of them. Returns the item's signature and doc text; pass `details: true` to also get the full structured blob."
    )]
    async fn get_doc(
        &self,
        Parameters(GetDocParams { name, details }): Parameters<GetDocParams>,
    ) -> String {
        let target = name.clone();
        let query = target.clone();
        let db = self.db.clone();
        let result = tokio::task::spawn_blocking(move || {
            let guard = db.lock().map_err(|e| e.to_string())?;
            guard.get_item_by_name_candidates(&query).map_err(|e| e.to_string())
        })
        .await;

        match result {
            Ok(Ok(rows)) => match rows.len() {
                0 => serde_json::to_string_pretty(&serde_json::json!({
                    "error": "not found",
                    "name": target,
                }))
                .unwrap(),
                1 => {
                    let summary = row_to_summary(rows.into_iter().next().unwrap(), details);
                    serde_json::to_string_pretty(&summary)
                        .unwrap_or_else(|e| error_json(&e.to_string()))
                }
                // Ambiguous simple name: report the candidates instead of silently picking one.
                _ => {
                    let mut candidates: Vec<serde_json::Value> = rows
                        .iter()
                        .map(|r| {
                            serde_json::json!({
                                "qual_name": r.qual_name,
                                "kind": r.kind.as_str(),
                                "signature": r.signature,
                            })
                        })
                        .collect();
                    // Keep the error bounded for names with many overloads.
                    if candidates.len() > 100 {
                        candidates.truncate(100);
                    }
                    serde_json::to_string_pretty(&serde_json::json!({
                        "error": "ambiguous",
                        "name": target,
                        "hint": "The name matches several items. Retry get_doc with a qualified name from the candidates list.",
                        "candidates": candidates,
                    }))
                    .unwrap_or_else(|e| error_json(&e.to_string()))
                }
            },
            Ok(Err(e)) => error_json(&e),
            Err(e) => error_json(&e.to_string()),
        }
    }

    /// List all modules in the documentation database.
    #[tool(
        description = "List all modules in the EDL documentation database, with their doc text. Use this for an overview of the library; list_items and get_module list the items inside."
    )]
    async fn list_modules(
        &self,
        Parameters(params): Parameters<ListModulesParams>,
    ) -> String {
        let details = params.details;
        let db = self.db.clone();
        let result = tokio::task::spawn_blocking(move || {
            let guard = db.lock().map_err(|e| e.to_string())?;
            guard.modules().map_err(|e| e.to_string())
        })
        .await;

        match result {
            Ok(Ok(rows)) => {
                let summaries: Vec<DocSummary> = rows
                    .into_iter()
                    .map(|row| row_to_summary(row, details))
                    .collect();
                serde_json::to_string_pretty(&summaries)
                    .unwrap_or_else(|e| error_json(&e.to_string()))
            }
            Ok(Err(e)) => error_json(&e),
            Err(e) => error_json(&e.to_string()),
        }
    }

    /// List all items in a specific module.
    #[tool(
        description = "List all documentation items (functions, types, variables, etc.) belonging to a module, including nested submodules. Use this to browse a module; note that items at the crate root (no module) are only listed by list_items."
    )]
    async fn get_module(
        &self,
        Parameters(GetModuleParams { name, details }): Parameters<GetModuleParams>,
    ) -> String {
        let target = name.clone();
        let db = self.db.clone();
        let result = tokio::task::spawn_blocking(move || {
            let guard = db.lock().map_err(|e| e.to_string())?;
            guard.list_module_items(&target).map_err(|e| e.to_string())
        })
        .await;

        match result {
            Ok(Ok(rows)) => {
                let filtered: Vec<DocSummary> = rows
                    .into_iter()
                    .map(|row| row_to_summary(row, details))
                    .collect();
                serde_json::to_string_pretty(&filtered)
                    .unwrap_or_else(|e| error_json(&e.to_string()))
            }
            Ok(Err(e)) => error_json(&e),
            Err(e) => error_json(&e.to_string()),
        }
    }

    /// List all documented items in the database, optionally filtered by kind.
    #[tool(
        description = "List all documented items in the database, optionally filtered by `kind` (fn, let, const, type, module). Unlike get_module, this also includes items at the crate root that belong to no module. Use it to browse the whole library; use search_docs to narrow by content."
    )]
    async fn list_items(
        &self,
        Parameters(ListItemsParams { kind, details }): Parameters<ListItemsParams>,
    ) -> String {
        let kind = match kind.as_deref().map(parse_kind).transpose() {
            Ok(k) => k,
            Err(e) => return error_json(&e),
        };
        let db = self.db.clone();
        let result = tokio::task::spawn_blocking(move || {
            let guard = db.lock().map_err(|e| e.to_string())?;
            guard.list_items(kind).map_err(|e| e.to_string())
        })
        .await;

        match result {
            Ok(Ok(rows)) => {
                let summaries: Vec<DocSummary> = rows
                    .into_iter()
                    .map(|row| row_to_summary(row, details))
                    .collect();
                serde_json::to_string_pretty(&summaries)
                    .unwrap_or_else(|e| error_json(&e.to_string()))
            }
            Ok(Err(e)) => error_json(&e),
            Err(e) => error_json(&e.to_string()),
        }
    }
}

#[tool_handler]
impl ServerHandler for DocMcpServer {
    fn get_info(&self) -> ServerInfo {
        ServerInfo::new(ServerCapabilities::builder().enable_tools().build()).with_instructions(
            "EDL documentation server. Recommended workflow: use search_docs to discover APIs \
             (prefix matching, optional kind filter), list_modules / list_items / get_module \
             to browse (summaries without the heavy blob by default), and get_doc with a \
             qualified name to fetch one item — if get_doc reports an 'ambiguous' error, retry \
             with a qualified name from its candidates list. Pass details: true only when you \
             need an item's full structured blob (fields, variants, generics).",
        )
    }
}

/// Starts the MCP server over stdio. Blocks until the client disconnects.
pub async fn serve_stdio(db: DocDb) -> Result<(), Box<dyn std::error::Error>> {
    let server = DocMcpServer::new(db);
    let running = server.serve(rmcp::transport::io::stdio()).await?;
    running.waiting().await?;
    Ok(())
}

/// Serves the MCP server over TCP using the Streamable HTTP transport (the MCP spec's network
/// transport). The endpoint is nested at `/mcp` on the given, already-bound listener. Blocks
/// until the process is terminated.
///
/// `bind` is the address the listener was bound to and decides how strict the `Host` header
/// validation is: loopback binds keep the default loopback-only validation (DNS-rebinding
/// protection); non-loopback binds disable it, so such deployments must be put behind a reverse
/// proxy with authentication.
pub async fn serve_http(
    listener: tokio::net::TcpListener,
    db: DocDb,
    bind: &str,
) -> Result<(), Box<dyn std::error::Error>> {
    let handle = Arc::new(Mutex::new(db));
    let session_manager = Arc::new(LocalSessionManager::default());
    let mut config = StreamableHttpServerConfig::default();
    if !bind_is_loopback(bind) {
        eprintln!(
            "warning: MCP HTTP endpoint is bound to non-loopback address {bind}; \
             Host-header validation is disabled. Put an authenticating reverse proxy in front \
             of this endpoint."
        );
        config = config.disable_allowed_hosts();
    }
    let service = StreamableHttpService::new(
        move || Ok(DocMcpServer::from_handle(handle.clone())),
        session_manager,
        config,
    );
    let app = axum::Router::new().nest_service("/mcp", service);
    axum::serve(listener, app).await?;
    Ok(())
}

/// Whether `bind` names a loopback address (anything else is treated as network-exposed).
fn bind_is_loopback(bind: &str) -> bool {
    matches!(bind, "127.0.0.1" | "localhost" | "::1")
}
