/*
 * EDLc, a compiler for the EDL programming language.
 * Copyright (C) 2026  Adrian Paskert
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
//! MCP server implementation for EDL documentation.
//!
//! Exposes four tools over the Model Context Protocol (stdio transport):
//!
//! - `search_docs(query, limit?)` — full-text search across item names, modules, signatures,
//!   and doc text.
//! - `get_doc(name)` — fetch a single documentation item by its (qualified) name.
//! - `list_modules()` — list all modules in the database.
//! - `get_module(name)` — list all items belonging to a module.
//!
//! ## What is MCP?
//!
//! The [Model Context Protocol](https://modelcontextprotocol.io/) is a standard protocol for
//! exposing tools, resources, and prompts to AI assistants. An MCP client (e.g. Claude Desktop,
//! Cursor, or any MCP-compatible LLM) launches this server as a child process and communicates
//! over stdin/stdout using JSON-RPC. The client can then call the tools listed above to search
//! and retrieve EDL documentation on behalf of the user.

use rmcp::{
    handler::server::{router::tool::ToolRouter, wrapper::Parameters},
    model::{ServerCapabilities, ServerInfo},
    schemars, tool, tool_handler, tool_router, ServerHandler, ServiceExt,
};
use serde::{Deserialize, Serialize};
use std::sync::{Arc, Mutex};

use edlc_doc_db::{DocDb, DocRow};

/// The MCP server. Holds a shared read-only handle to the documentation database and a
/// tool router generated by the `#[tool_router]` macro.
///
/// `DocDb` contains a `rusqlite::Connection` which is `Send` but not `Sync`. We wrap it in
/// `std::sync::Mutex` to satisfy the `ServerHandler: Sync` bound. The lock is never held across
/// an `.await` point — all DB work goes through `tokio::task::spawn_blocking`.
pub struct DocMcpServer {
    db: Arc<Mutex<DocDb>>,
    /// Generated by `#[tool_router]` — stores tool metadata for dispatch.
    tool_router: ToolRouter<Self>,
}

impl DocMcpServer {
    /// Creates a new MCP server backed by the given database.
    pub fn new(db: DocDb) -> Self {
        DocMcpServer {
            db: Arc::new(Mutex::new(db)),
            tool_router: Self::tool_router(),
        }
    }
}

// --- Tool parameter structs ---

#[derive(Debug, Deserialize, schemars::JsonSchema)]
struct SearchDocsParams {
    /// The search query. Matched against item names, module paths, signatures, and doc text
    /// using SQLite FTS5 full-text search.
    query: String,
    /// Maximum number of results to return. Defaults to 20.
    #[serde(default = "default_search_limit")]
    limit: usize,
}

fn default_search_limit() -> usize {
    20
}

#[derive(Debug, Deserialize, schemars::JsonSchema)]
struct GetDocParams {
    /// The name of the item to fetch. Can be a simple name (e.g. "add") or a qualified name
    /// (e.g. "example::add").
    name: String,
}

#[derive(Debug, Deserialize, schemars::JsonSchema)]
struct GetModuleParams {
    /// The name of the module whose items should be listed.
    name: String,
}

// --- Result type ---

#[derive(Debug, Serialize)]
struct DocSummary {
    id: i64,
    kind: String,
    name: String,
    qual_name: String,
    module: Option<String>,
    signature: String,
    doc_text: String,
    /// The full serde-JSON of the original `Item`, containing all structured fields including
    /// `async_return`, `modifiers`, params, etc. Deserializable by the client if it needs
    /// details beyond the summary fields.
    blob: String,
}

impl From<DocRow> for DocSummary {
    fn from(row: DocRow) -> Self {
        DocSummary {
            id: row.id,
            kind: row.kind.as_str().to_string(),
            name: row.name,
            qual_name: row.qual_name,
            module: row.module,
            signature: row.signature,
            doc_text: row.doc_text,
            blob: row.blob,
        }
    }
}

fn error_json(msg: &str) -> String {
    serde_json::to_string_pretty(&serde_json::json!({ "error": msg })).unwrap()
}

// --- Tools ---

#[tool_router]
impl DocMcpServer {
    /// Search EDL documentation by full-text query.
    #[tool(description = "Search EDL documentation items (functions, types, variables, constants, modules) by full-text query. Returns matching items with their signatures and doc text.")]
    async fn search_docs(
        &self,
        Parameters(SearchDocsParams { query, limit }): Parameters<SearchDocsParams>,
    ) -> String {
        let db = self.db.clone();
        let result = tokio::task::spawn_blocking(move || {
            let guard = db.lock().map_err(|e| e.to_string())?;
            guard.search(&query, limit).map_err(|e| e.to_string())
        })
        .await;

        match result {
            Ok(Ok(rows)) => {
                let summaries: Vec<DocSummary> = rows.into_iter().map(Into::into).collect();
                serde_json::to_string_pretty(&summaries).unwrap_or_else(|e| error_json(&e.to_string()))
            }
            Ok(Err(e)) => error_json(&e),
            Err(e) => error_json(&e.to_string()),
        }
    }

    /// Get a single documentation item by name.
    #[tool(description = "Fetch a single EDL documentation item by its name (simple or qualified). Returns the item's full details including its signature and doc text.")]
    async fn get_doc(
        &self,
        Parameters(GetDocParams { name }): Parameters<GetDocParams>,
    ) -> String {
        let target = name.clone();
        let db = self.db.clone();
        let result = tokio::task::spawn_blocking(move || {
            let guard = db.lock().map_err(|e| e.to_string())?;
            guard.list_items(None).map_err(|e| e.to_string())
        })
        .await;

        match result {
            Ok(Ok(all)) => {
                let found = all.into_iter().find(|row| row.qual_name == target || row.name == target);
                match found {
                    Some(row) => {
                        let summary = DocSummary::from(row);
                        serde_json::to_string_pretty(&summary)
                            .unwrap_or_else(|e| error_json(&e.to_string()))
                    }
                    None => serde_json::to_string_pretty(&serde_json::json!({
                        "error": "not found",
                        "name": target,
                    }))
                    .unwrap(),
                }
            }
            Ok(Err(e)) => error_json(&e),
            Err(e) => error_json(&e.to_string()),
        }
    }

    /// List all modules in the documentation database.
    #[tool(description = "List all modules in the EDL documentation database. Returns an array of module names with their doc text.")]
    async fn list_modules(&self) -> String {
        let db = self.db.clone();
        let result = tokio::task::spawn_blocking(move || {
            let guard = db.lock().map_err(|e| e.to_string())?;
            guard.modules().map_err(|e| e.to_string())
        })
        .await;

        match result {
            Ok(Ok(rows)) => {
                let summaries: Vec<DocSummary> = rows.into_iter().map(Into::into).collect();
                serde_json::to_string_pretty(&summaries).unwrap_or_else(|e| error_json(&e.to_string()))
            }
            Ok(Err(e)) => error_json(&e),
            Err(e) => error_json(&e.to_string()),
        }
    }

    /// List all items in a specific module.
    #[tool(description = "List all documentation items (functions, types, variables, etc.) belonging to a specific module. Returns matching items with their signatures and doc text.")]
    async fn get_module(
        &self,
        Parameters(GetModuleParams { name }): Parameters<GetModuleParams>,
    ) -> String {
        let target = name.clone();
        let db = self.db.clone();
        let result = tokio::task::spawn_blocking(move || {
            let guard = db.lock().map_err(|e| e.to_string())?;
            guard.list_items(None).map_err(|e| e.to_string())
        })
        .await;

        match result {
            Ok(Ok(all)) => {
                let filtered: Vec<DocSummary> = all
                    .into_iter()
                    .filter(|row| {
                        row.module.as_deref() == Some(target.as_str())
                            || row.qual_name.starts_with(&format!("{}::", target))
                    })
                    .map(Into::into)
                    .collect();
                serde_json::to_string_pretty(&filtered).unwrap_or_else(|e| error_json(&e.to_string()))
            }
            Ok(Err(e)) => error_json(&e),
            Err(e) => error_json(&e.to_string()),
        }
    }
}

#[tool_handler]
impl ServerHandler for DocMcpServer {
    fn get_info(&self) -> ServerInfo {
        ServerInfo::new(ServerCapabilities::builder().enable_tools().build()).with_instructions(
            "EDL documentation server. Use search_docs to search for items, get_doc to fetch \
             a specific item, list_modules to see all modules, and get_module to list items \
             in a module.",
        )
    }
}

/// Starts the MCP server over stdio. Blocks until the client disconnects.
pub async fn serve_stdio(db: DocDb) -> Result<(), Box<dyn std::error::Error>> {
    let server = DocMcpServer::new(db);
    let running = server.serve(rmcp::transport::io::stdio()).await?;
    running.waiting().await?;
    Ok(())
}
